# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
settings: &settings
  adapter: postgresql
  encoding: unicode
  database: testdrivenrails
  pool: 5

  username: postgres
  password: postgres
  host: localhost



development:
  <<: *settings
test:
  <<: *settings
production:
  <<: *settings
